### ISSUE TITLE
 For 10 minutes of the game, the logs weigh 1 gigabyte by errors

### ISSUE THREAD

**Issue by EurekaMan** [DustinRepo/JexClient-main#1]
[22:24:18] [main/INFO] (Minecraft) [STDERR]: java.lang.reflect.InvocationTargetException
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	at jdk.internal.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	at me.dustin.events.EventManager.lambda$run$0(EventManager.java:83)
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	at me.dustin.events.EventManager.run(EventManager.java:80)
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	at me.dustin.events.api.EventAPI.run(EventAPI.java:34)
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	at me.dustin.events.core.Event.run(Event.java:19)
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	at net.minecraft.client.gui.hud.InGameHud.handler$zhn000$draw(InGameHud.java:1779)
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud.java:324)
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:470)
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1007)
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:624)
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:187)
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
[22:24:18] [main/INFO] (Minecraft) [STDERR]: Caused by: java.lang.NullPointerException
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	at me.dustin.jex.module.impl.render.Hud.drawWatermark(Hud.java:284)
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	at me.dustin.jex.module.impl.render.Hud.runRenderMethod(Hud.java:146)
[22:24:18] [main/INFO] (Minecraft) [STDERR]: 	... 22 more

**Comment by DustinRepo** [comment]
I believe I can see the issue causing this. It should be fixed by next update.
